name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Only trigger workflow on push to main branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MUD_09EE94110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # For Azure PR comment status, required
          action: "upload"
          app_location: "/"                       # Your Vite project root
          output_location: "dist"                 # Vite build output folder
